name: Test GO
on:
  push:
    branches: ["github-actions-setup"]
jobs:
  test-app:    
    runs-on: ubuntu-slim
    defaults:
      run:
        working-directory: ./backend
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v6
        
      - name: Install Go
        uses: actions/setup-go@v7.0.0
        with:
          go-version-file: './backend/go.mod'
          cache: true
          cache-dependency-path: './backend/go.sum'

      - name: Build
        run: go run -o ./bin/ ./...
        

      - name: List Dir
        run: ls ./bin -la
        
      - name: Test
        run: go test ./...
        
  
